# Sveltia CMS Configuration
backend:
  name: github
  branch: main
  repo: RickyRivas/buildkit-v1 # or master, depending on your default branch

# Media files configuration
media_folder: "static/images"
public_folder: "/images"

# Collections define the content types
collections:
  # Pages collection for main site pages
  - name: "pages"
    label: "Pages"
    folder: "src/lib/cms/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          hint: "URL path for this page",
        }
      - {
          label: "Layout",
          name: "layout",
          widget: "select",
          options: ["standard", "full-width", "landing"],
          default: "standard",
        }
      - {
          label: "Meta Title",
          name: "meta_title",
          widget: "string",
          required: false,
        }
      - {
          label: "Meta Description",
          name: "meta_description",
          widget: "text",
          required: false,
        }
      - {
          label: "Featured Image",
          name: "featured_image",
          widget: "image",
          required: false,
        }
      - {
          label: "Image Alt Text",
          name: "image_alt",
          widget: "string",
          required: false,
        }
      - {
          label: "Show in Navigation",
          name: "show_in_nav",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Navigation Order",
          name: "nav_order",
          widget: "number",
          default: 0,
          hint: "Lower numbers appear first",
        }
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: true,
        }
      - { label: "Content", name: "body", widget: "markdown" }

  # Blog posts collection
  - name: "blog"
    label: "Blog Posts"
    folder: "src/lib/cms/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Admin" }
      - {
          label: "Featured Image",
          name: "featured_image",
          widget: "image",
          required: false,
        }
      - {
          label: "Image Alt Text",
          name: "image_alt",
          widget: "string",
          required: false,
        }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - {
          label: "Meta Title",
          name: "meta_title",
          widget: "string",
          required: false,
        }
      - {
          label: "Meta Description",
          name: "meta_description",
          widget: "text",
          required: false,
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          required: false,
          hint: "Add relevant tags for this post",
        }
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: false,
        }
      - { label: "Content", name: "body", widget: "markdown" }

  # Site settings - single file configuration
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "src/lib/settings/general.json"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
          - {
              label: "Site Description",
              name: "site_description",
              widget: "text",
            }
          - { label: "Site URL", name: "site_url", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image", required: false }
          - {
              label: "Favicon",
              name: "favicon",
              widget: "image",
              required: false,
            }
          - {
              label: "Contact Email",
              name: "contact_email",
              widget: "string",
              pattern:
                [
                  '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',
                  "Must be a valid email",
                ],
            }
          - {
              label: "Phone Number",
              name: "phone",
              widget: "string",
              required: false,
            }
          - {
              label: "Address",
              name: "address",
              widget: "text",
              required: false,
            }

      - label: "Navigation"
        name: "navigation"
        file: "src/lib/settings/navigation.json"
        fields:
          - label: "Main Navigation"
            name: "main_nav"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Path", name: "path", widget: "string" }
              - {
                  label: "Icon Path",
                  name: "iconPath",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Show in Nav",
                  name: "showInNav",
                  widget: "boolean",
                  default: true,
                }
              - label: "Children"
                name: "children"
                widget: "list"
                required: false
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Path", name: "path", widget: "string" }
                  - {
                      label: "Icon Path",
                      name: "iconPath",
                      widget: "string",
                      required: false,
                    }
                  - {
                      label: "Show in Nav",
                      name: "showInNav",
                      widget: "boolean",
                      default: true,
                    }
                  - label: "Sub-Children"
                    name: "children"
                    widget: "list"
                    required: false
                    fields:
                      - { label: "Name", name: "name", widget: "string" }
                      - { label: "Path", name: "path", widget: "string" }
                      - {
                          label: "Icon Path",
                          name: "iconPath",
                          widget: "string",
                          required: false,
                        }
                      - {
                          label: "Show in Nav",
                          name: "showInNav",
                          widget: "boolean",
                          default: true,
                        }

      - label: "SEO Settings"
        name: "seo"
        file: "src/lib/settings/seo.json"
        fields:
          - {
              label: "Default Meta Title",
              name: "default_title",
              widget: "string",
            }
          - {
              label: "Default Meta Description",
              name: "default_description",
              widget: "text",
            }
          - {
              label: "Open Graph Image",
              name: "og_image",
              widget: "image",
              required: false,
            }
          - {
              label: "Twitter Handle",
              name: "twitter_handle",
              widget: "string",
              required: false,
            }
          - {
              label: "Google Analytics ID",
              name: "ga_id",
              widget: "string",
              required: false,
            }

  # Custom sections for reusable components
  - name: "sections"
    label: "Page Sections"
    folder: "src/lib/sections"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Section Name", name: "name", widget: "string" }
      - {
          label: "Section ID",
          name: "section_id",
          widget: "string",
          hint: "Unique identifier for this section",
        }
      - {
          label: "Section Type",
          name: "type",
          widget: "select",
          options:
            ["hero", "about", "services", "testimonials", "contact", "custom"],
        }
      - {
          label: "Background Color",
          name: "bg_color",
          widget: "string",
          required: false,
          hint: "CSS color value",
        }
      - {
          label: "Background Image",
          name: "bg_image",
          widget: "image",
          required: false,
        }
      - { label: "Title", name: "title", widget: "string", required: false }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - {
          label: "Content",
          name: "content",
          widget: "markdown",
          required: false,
        }
      - {
          label: "Button Text",
          name: "button_text",
          widget: "string",
          required: false,
        }
      - {
          label: "Button URL",
          name: "button_url",
          widget: "string",
          required: false,
        }
      - {
          label: "Additional Settings",
          name: "settings",
          widget: "object",
          required: false,
          fields:
            [
              {
                label: "Full Width",
                name: "full_width",
                widget: "boolean",
                default: false,
              },
              {
                label: "Center Content",
                name: "center_content",
                widget: "boolean",
                default: false,
              },
              {
                label: "Custom CSS Class",
                name: "css_class",
                widget: "string",
                required: false,
              },
            ],
        }
# Optional: customize the CMS interface
# display_url: https://yoursite.netlify.app
# logo_url: /images/admin-logo.png
# Optional: enable editorial workflow for content approval
# publish_mode: editorial_workflow
